# path or URL to sample sheet (TSV format, columns: sample, condition, ...)
# samples: config/samples.tsv
# we do not have this here

reference: resources/chr1.pan.fa.a2fb268.4030258.6a1ecc2.smooth.gfa.gz
gtf: resources/gencode.v40.annotation.gtf.gz

odgi:
  threads_odgi: 32
  mem_odgi: 64000
  resource_prefix: 'chr1.pan.fa.a2fb268.4030258.6a1ecc2.smooth'
  region: 'grch38#chr1:103550000-103800000'

