#!vim set synax=python


#
#cat ../output/selected_indivs_AMY_region.fa.gz | gzip -d >AMY1A_region_seq.fa
#/Users/petersudmant/Documents/science/sudmantlab/code/fastatools/target/debug/fastatools  split AMY1A_region_seq.fa ./split_fastas

# minimap2 -x splice:hq -uf ./split_fastas/chr1_hg19_103998686_104406594_0.fa ./amylase_seqs/Homo_sapiens_ENST00000361355_8_sequence.fa

configfile: "config.json"
configfile: "../config.json"
rule all:
    input:
        "output/gene_alns.paf"


rule split_fa:
    output:
        "split_fastas/idx.txt"
    run:
        cmd="cat ../output/selected_indivs_AMY_region.fa.gz | gzip -d >AMY1A_region_seq.fa"
        shell(cmd)
        cmd="/Users/petersudmant/Documents/science/sudmantlab/code/fastatools/target/debug/fastatools  split AMY1A_region_seq.fa ./split_fastas"
        shell(cmd)


rule make_alns:
    input:
        "split_fastas/idx.txt"
    output:
        "output/gene_alns.paf"
    run:   
        #cmd = "minimap2 -N 30 -x splice:hq -uf {ref_hap} {gene} >>{out}" 
        cmd = "minimap2 -N 30 -x splice:hq -uf ./split_fastas/{ref_hap}.fa {gene} >>{out}" 
        #for hap in config["haps"]:
        for hap in config["samples"]:
            for g in config["genes"]:
                print(hap, g)
                shell(cmd.format(ref_hap=hap,
                                 gene=g,
                                 out = output[0]))


