#!vim set syntax=python

rule all:
    input:
        "output/input_chr1.anc"

rule run_relate:
    input:
        haps = "data/input_chr1.haps.gz",
        sample = "data/input_chr1.sample.gz",
        dist = "data/input_chr1.dist.gz"
    output:
        anc = "output/input_chr1.anc"
    run:
        bin_path = "/global/scratch/users/psudmant/software/relate_v1.1.9_x86_64_static/bin/Relate"
        map="/global/scratch/p2p3/sudmantlab/human_diversity/1KG30X/hg19/1000GP_Phase3/genetic_map_chr1_combined_b37.txt"
        cmd = ("rm -r output;"
               "{bin_path} "
               "--mode All "
               "-m 1.25e-8 "
               "-N 30000 "
               "--haps {haps} "
               "--sample {sample} "
               "--map {map} "
               "--seed 1 "
               "-o output"
               "".format(bin_path=bin_path,
                         haps=input.haps,
                         sample=input.sample,
                         map=map))
        shell(cmd)

rule make_inputs_from_hap:
    input:
        haps="data/chr1.haps",
        sample="data/chr1.sample"
    output:
        o_haps = "data/input_chr1.haps.gz",
        o_sample = "data/input_chr1.sample.gz",
        o_dist = "data/input_chr1.dist.gz"
    run:
        fn_anc = "/global/scratch/p2p3/sudmantlab/human_diversity/1KG30X/hg19/human_ancestor_GRCh37_e59/human_ancestor_1.fa"
        bin_path = "/global/scratch/users/psudmant/software/relate_v1.1.9_x86_64_static/scripts/PrepareInputFiles/PrepareInputFiles.sh"
        fn_mask = "/global/scratch/p2p3/sudmantlab/human_diversity/1KG30X/hg19/masks/20141020.combined_mask.whole_genome.bed"
        pop_labels = ""
        cmd = ("{bin_path} "
                "--haps {haps} "
                "--sample {sample} "
                "--ancestor {fn_anc} "
                "--mask {fn_mask} "
                "--poplabels /global/scratch/p2p3/sudmantlab/human_diversity/1KG30X/hg19/1000GP_Phase3/1000GP_Phase3.sample "
                "-o data/input_chr1"
                "".format(bin_path=bin_path,
                          haps=input.haps,
                          sample=input.sample,
                          fn_anc = fn_anc,
                          fn_mask=fn_mask))
        shell(cmd)


rule make_haps_from_hap:
    output:
        haps="data/chr1.haps",
        sample="data/chr1.sample"
    run:
        cmd = ("/global/scratch/users/psudmant/software/relate_v1.1.9_x86_64_static/bin/RelateFileFormats "
                "--mode ConvertFromHapLegendSample "
                "--haps {haps} "
                "--sample {sample} "
                "--chr 1 "
                "-i /global/scratch/p2p3/sudmantlab/human_diversity/1KG30X/hg19/1000GP_Phase3/1000GP_Phase3_chr1 "
                "".format(haps=output.haps,
                          sample=output.sample))
        shell(cmd)

#vcf
#rule make_haps_from_vcf:
#    output:
#        haps="data/chr1.haps",
#        sample="data/chr1.sample"
#    run:
#        cmd = ("/global/scratch/users/psudmant/software/relate_v1.1.9_x86_64_static/bin/RelateFileFormats "
#                "--mode ConvertFromVcf "
#                "--haps {haps} "
#                "--sample {sample} "
#                #"-i ../input/1.neo.impute.1000g "
#                "-i /global/scratch/p2p3/sudmantlab/human_diversity/1KG30X/NYGC_VCFs/PhasedVCFs/1kGP_high_coverage_Illumina.chr1.filtered.SNV_INDEL_SV_phased_panel "
#                "".format(haps=output.haps,
#                          sample=output.sample))
#        shell(cmd)

