---
title: "Untitled"
output: html_document
date: "2022-10-02"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Code to analyze copy numbers across populations and over time

```{r cars}
library(tidyverse)
library(PNWColors)
outdir="/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/read_depth_genotyping/genotyping/output"
fn_gts = paste(outdir,"/genotypes.raw.tsv",sep="")
t_genotypes = read.table(fn_gts, header=T, sep="\t")

ancient_info = read.table("/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/haplotype_analysis/metadata/ancient_info.tsv",header=T,sep="\t") %>%
  mutate(ID = sample, age=ageAverage) %>%
  dplyr::select(ID, age)

t_genotypes = left_join(t_genotypes,ancient_info,by="ID") %>%
  mutate(age=ifelse(dataset!="StoneAgeAncient",0,as.numeric(age))) %>%
  filter(sample!="StoneAgeAncient.VK117.NorthernEurope.Yamnaya") %>%
  mutate(p2 = ifelse(dataset=="Archaic","Archaic",p2))
  #mutate(gt = round(gt))

#filter this individual, looks funky, need to check more
#StoneAgeAncient.VK117.NorthernEurope.Yamnaya	

#unique(t_genotypes$dataset)
t_genotypes %>% filter(grepl("Archaic",sample))
t_genotypes %>% filter(grepl("SGDP",sample)) %>% dplyr::select(sample) %>% unique()
```

## Including Plots

You can also embed plots, for example:

```{r}
library(ggjoy)
#install.packages("cowplot")
library(cowplot)
library(ggridges)
library(broom)
library(rstatix)
lmp <- function (modelobject) {
    if (class(modelobject) != "lm") stop("Not an object of class 'lm' ")
    f <- summary(modelobject)$fstatistic
    p <- pf(f[1],f[2],f[3],lower.tail=F)
    attributes(p) <- NULL
    return(p)
}

```
```{r}

WEAs = c("Archaic",
         "WEA",
         "Hunter-GathererE",
         "Hunter-GathererW",
         "Yamnaya",
         "EarlyFarmer")
t_amy = t_genotypes %>% 
          #filter(name=="amy1_sum") %>% 
          #filter(name=="AMY2A") %>%
          #filter(name=="AMY2B") %>%
          #filter(age<15000) %>%
          mutate(p3 = ifelse(p2 %in% WEAs,
                              "European",
                              "not European")) %>%
          mutate(nage=-1*age,
                 gt_round=round(gt)) %>%
          rowwise() %>%
          mutate(j_age = ifelse(age==0,age+runif(1,-100,100),age))
          #mutate(gt=gt_round)

order = c("WEA",  
          "Yamnaya",
          "EarlyFarmer",
          "Hunter-GathererW", 
          "Hunter-GathererE",       
          "Archaic",
          "OCN",
          "EA",
          "CAS",
          "SA",
          "AMR",
          "AFR")

t_amy$p2 = factor(t_amy$p2, levels=rev(order))

curr_gene = "amy1_sum"  
#curr_gene = "AMY2B"  
#curr_gene = "AMY2A"  

t_sum = t_amy %>% 
       group_by(p2,p3,name) %>%
       summarize(mu = mean(gt),
                 sdev = sd(gt),
                 n = n()) %>%
       mutate(sem = sdev/sqrt(n)) %>%
  ungroup()


combos = unique(WEAs) %>%
  combn(2, simplify = F) %>%
  set_names(map_chr(., ~ paste(., collapse = "_"))) 



#https://stackoverflow.com/questions/56361724/multiple-tests-with-pairwise-combinations-using-dplyr-tidyverse

  
colors = c(pnw_palette("Bay",6), pnw_palette("Sunset2",7))
outdir="/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/read_depth_genotyping/genotyping/output_figures/"

for (curr_gene in c("amy1_sum","AMY2B","AMY2A")){
#for (curr_gene in c("amy1_sum")){
  t_sum_plot = t_sum %>% filter(name==curr_gene)
  t_amy_plot = t_amy %>% filter(name==curr_gene) %>% 
    dplyr::select(gt,p2,p3)
  fn_out = paste(outdir,"/genotype_density_",curr_gene,".pdf",sep="")
  
  p_values = map_df(combos, function(y) {
              filter(t_amy_plot, p2 %in% y) %>% 
                wilcox.test(gt ~ p2, data = .) %>% 
                broom::tidy()
              }, .id = "contrast") %>%
            filter(grepl("WEA",contrast)) %>%
            mutate(p_adj = p.adjust(p.value)) %>%
            mutate(p = str_replace(contrast,"WEA_","")) %>%
            mutate(p = str_replace(p,"_WEA","")) %>%
            mutate(label = ifelse(p_adj>0.05,"N.S",
                                  paste("P==",signif(p_adj,2)))) %>%
            mutate(p3="European") %>%
            mutate(x=case_when(
              curr_gene=="amy1_sum" ~ 15,
              curr_gene=="AMY2B" ~ 4,
              curr_gene=="AMY2A" ~ 4.5,
              TRUE ~0
            ))
            
  g=ggplot(t_amy %>% filter(name==curr_gene))
  g=g+geom_density_ridges(aes(x=gt,y=p2,fill=p2,color=p2),
                        binwidth=.1,
                        alpha=.1,
                        size=.5,
                        scale=.7,adjust=.01)+
    geom_point(aes(x=gt,y=p2),shape="|",size=1,alpha=.25,position=position_nudge(y=-.25))+
    geom_errorbarh(aes(xmin=mu-sem,xmax=mu+sem,y=p2,color=p2),data=t_sum_plot,height=0.1)+
    geom_point(aes(x=mu,y=p2,color=p2),data=t_sum_plot,size=1)+
    geom_point(aes(x=mu,y=p2),data=t_sum_plot,size=.1,color="white")+
    geom_text(aes(x=x,y=p,label=label),
              parse=TRUE,
              data=p_values,
              size=2,
              hjust=0,
              position=position_nudge(y=.35))+
    theme_bw(base_size=6)+
    scale_x_continuous("copy genotype",breaks=seq(0,20,2))+
    scale_y_discrete("")+
    facet_grid(p3~.,shrink = TRUE,drop = TRUE,scales="free_y")+
    theme(strip.background=element_blank())+
    scale_color_manual(values=colors)+
    scale_fill_manual(values=colors)+
    theme(legend.position="None")
  pdf(fn_out,width=2.5,height=2)
  print(g)
  dev.off()  
  
}

p_values


```


```{r}

########NOTE we jittered the moderns
outdir="/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/read_depth_genotyping/genotyping/output_figures/trajectories"

c = pnw_palette("Bay",5)[5]
colors = pnw_palette("Sunset",6)

t_amy1 = t_genotypes %>% 
          filter(name=="amy1_sum") %>% 
          filter(age<15000) %>%
          filter(p2 %in% c("WEA",
                           "Hunter-GathererE",
                           "Hunter-GathererW",
                           "Yamnaya",
                           "EarlyFarmer")) %>%
          mutate(nage=-1*age,
                 gt_round=round(gt)) %>%
          rowwise() %>%
          mutate(j_age = ifelse(age==0,age+runif(1,-100,100),age))

m=lm(gt~nage,data=t_amy1)
p=lmp(m)
df_label = data.frame(x=-11000,y=16.5,label=paste("P==",signif(p,3)))

breaks = seq(-15000,0,5000)
labels = paste(breaks/1000)
label = "kyr BP"

fn_out = paste(outdir,"/genotypes_amy1_by_age.pdf",sep="")

#pdf(fn_out,width=2,height=1.75)
g1=ggplot(t_amy1)
g1=g1+geom_point(aes(x=-j_age, y=gt,color=p2),size=.01)+#,alpha=.25
  geom_smooth(aes(x=-age, y=gt),color=c)+
  geom_text(aes(x=x,
                y=y,
                label=label),
            parse=TRUE,
            size=3,
            data=df_label,
            hjust=0)+
  scale_y_continuous("AMY1 copy",breaks=seq(0,16,2))+
  scale_x_continuous(label,labels=labels,breaks=breaks)+
  theme_bw()+
  theme(legend.position="None")+
  scale_color_manual(values=colors)
#print(g1)
#dev.off()

fn_out = paste(outdir,"/genotypes_amy1_by_age_traj.pdf",sep="")
#pdf(fn_out,width=2,height=1.75)
g2=ggplot(t_amy1)
g2=g2+geom_smooth(aes(x=-age, y=gt),color=c)+
  scale_y_continuous("AMY1 copy",breaks=seq(4,7,1))+
  scale_x_continuous(label,labels=labels,breaks=breaks)+
  theme_bw()
#print(g2)
#dev.off()

fn_out = paste(outdir,"/genotypes_amy1_by_age_both.pdf",sep="")
pdf(fn_out,width=4,height=1.75)
g3=plot_grid(g1,g2,ncol=2,rel_widths=c(1,1),rel_heights=c(1,1))
print(g3)
dev.off()
```
```{r}

########NOTE we jittered the moderns
outdir="/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/read_depth_genotyping/genotyping/output_figures/trajectories"

c = pnw_palette("Bay",5)[5]
colors = pnw_palette("Bay",5)[1:4]

t_amy2A = t_genotypes %>% 
          filter(name=="AMY2A") %>% 
          filter(age<15000) %>%
          filter(p2 %in% c("WEA",
                           "Hunter-GathererE",
                           "Hunter-GathererW",
                           "Yamnaya",
                           "EarlyFarmer")) %>%
          mutate(nage=-1*age,
                 gt_round=round(gt)) %>%
          rowwise() %>%
          mutate(j_age = ifelse(age==0,age+runif(1,-100,100),age))

m=lm(gt~nage,data=t_amy2A)
p=lmp(m)
df_label = data.frame(x=-11000,y=5,label=paste("P==",signif(p,3)))

breaks = seq(-15000,0,5000)
labels = paste(breaks/1000)
label = "kyr BP"

fn_out = paste(outdir,"/genotypes_amy2A_by_age.pdf",sep="")

#pdf(fn_out,width=2,height=1.75)
g1=ggplot(t_amy2A)
g1=g1+geom_point(aes(x=-j_age, y=gt),alpha=.25,size=.01)+
  geom_smooth(aes(x=-age, y=gt),color=c)+
  geom_text(aes(x=x,
                y=y,
                label=label),
            parse=TRUE,
            size=3,
            data=df_label,
            hjust=0)+
  scale_y_continuous("AMY2A copy",breaks=seq(0,5,1))+
  scale_x_continuous(label,labels=labels,breaks=breaks)+
  theme_bw()+
  theme(legend.position="None")
#print(g1)
#dev.off()

#fn_out = paste(outdir,"/genotypes_amy2A_by_age_traj.pdf",sep="")
#pdf(fn_out,width=2,height=1.75)
g2=ggplot(t_amy2A)
g2=g2+geom_smooth(aes(x=-age, y=gt),color=c)+
  #scale_y_continuous("AMY1 copy",breaks=seq(,7,1))+
  scale_x_continuous(label,labels=labels,breaks=breaks)+
  theme_bw()
#print(g2)
#dev.off()

fn_out = paste(outdir,"/genotypes_amy2A_by_age_both.pdf",sep="")
pdf(fn_out,width=4,height=1.75)
g3=plot_grid(g1,g2,ncol=2,rel_widths=c(1,1),rel_heights=c(1,1))
print(g3)
dev.off()

#HGDP01406
#t_genotypes %>% filter(ID=="HGDP01406")
#filter(name=="AMY2A") %>% arrange(-gt)
```
```{r}

outdir="/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/read_depth_genotyping/genotyping/output_figures/trajectories"

c = pnw_palette("Bay",5)[5]
colors = pnw_palette("Bay",5)[1:4]

t_amy2B = t_genotypes %>% 
          filter(name=="AMY2B") %>% 
          filter(age<15000) %>%
          filter(p2 %in% c("WEA",
                           "Hunter-GathererE",
                           "Hunter-GathererW",
                           "Yamnaya",
                           "EarlyFarmer")) %>%
          mutate(nage=-1*age,
                 gt_round=round(gt)) %>%
          rowwise() %>%
          mutate(j_age = ifelse(age==0,age+runif(1,-100,100),age))

m=lm(gt~nage,data=t_amy2B)
p=lmp(m)
df_label = data.frame(x=-11000,y=4,label=paste("P==",signif(p,3)))

breaks = seq(-15000,0,5000)
labels = paste(breaks/1000)
label = "kyr BP"

fn_out = paste(outdir,"/genotypes_amy2B_by_age.pdf",sep="")

#pdf(fn_out,width=2,height=1.75)
g1=ggplot(t_amy2B)
g1=g1+geom_point(aes(x=-j_age, y=gt),alpha=.25,size=.01)+
  geom_smooth(aes(x=-age, y=gt),color=c)+
  geom_text(aes(x=x,
                y=y,
                label=label),
            parse=TRUE,
            size=3,
            data=df_label,
            hjust=0)+
  scale_y_continuous("AMY2B copy",breaks=seq(0,5,1))+
  scale_x_continuous(label,labels=labels,breaks=breaks)+
  theme_bw()+
  theme(legend.position="None")
print(g1)
#dev.off()

#fn_out = paste(outdir,"/genotypes_amy2A_by_age_traj.pdf",sep="")
#pdf(fn_out,width=2,height=1.75)
g2=ggplot(t_amy2B)
g2=g2+geom_smooth(aes(x=-age, y=gt),color=c)+
  #scale_y_continuous("AMY1 copy",breaks=seq(,7,1))+
  scale_x_continuous(label,labels=labels,breaks=breaks)+
  theme_bw()
#print(g2)
#dev.off()

fn_out = paste(outdir,"/genotypes_amy2B_by_age_both.pdf",sep="")
pdf(fn_out,width=4,height=1.75)
g3=plot_grid(g1,g2,ncol=2,rel_widths=c(1,1),rel_heights=c(1,1))
print(g3)
dev.off()

#t_amy2B %>% arrange(-gt)
#t_amy2A %>% arrange(-gt)
#StoneAgeAncient.VK117.NorthernEurope.Yamnaya	
```





```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
