---
title: "Untitled"
output: html_document
date: '2022-07-15'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r, fig.height=2,fig.width=6}
library(tidyverse)

outdir="/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/read_depth_genotyping/genotyping/output"
fn_gts = "/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/read_depth_genotyping/d4_cvg_analysis/d4_to_windowed_cvg/output/genotype/genotypes.tsv"


ancient_qc = read.table("/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/info/ancients_passed_QC.tsv", header=T,sep="\t")

t_gt = read.table(fn_gts, sep="\t",header=T) %>%
       dplyr::select(locus,cp,sample) %>%
       pivot_wider(values_from = "cp",names_from="locus") %>%
        mutate(amy1_sum = AMY1A + AMY1B + AMY1C) %>%
        pivot_longer(cols=-c("sample"),values_to="gt") %>%
        separate(sample,c("dataset","ID","p1","p2"),sep="\\.",remove=FALSE) %>%
  filter((dataset!="StoneAgeAncient")|ID %in% ancient_qc$sample)

# g=ggplot(t_gt %>% filter(name %in% c("amy1_sum","AMY2A","AMY2B")))
# g+geom_histogram(aes(x=gt),binwidth=0.05)+
#   facet_grid(name~dataset,scales="free")+
#   theme_bw(base_size=8)+
#   scale_x_continuous(breaks=seq(0,18,1))


g=ggplot(t_gt %>% filter(name %in% c("amy1_sum","AMY2A","AMY2B")) %>% filter(grepl("1KG",sample)))
g+geom_histogram(aes(x=gt),binwidth=0.05)+
  facet_wrap(~name,scales="free",nrow=1)+
  theme_bw(base_size=8)+
  scale_x_continuous(breaks=seq(0,18,1))

g=ggplot(t_gt %>% filter(name %in% c("amy1_sum","AMY2A","AMY2B")) %>% filter(grepl("HGDP",sample)))
g+geom_histogram(aes(x=gt),binwidth=0.05)+
  facet_wrap(~name,scales="free",nrow=1)+
  theme_bw(base_size=8)+
  scale_x_continuous(breaks=seq(0,18,1))

g=ggplot(t_gt %>% filter(name %in% c("amy1_sum","AMY2A","AMY2B")) %>% filter(grepl("HGDP",sample)))
g+geom_histogram(aes(x=gt*0.97),binwidth=0.05,color='blue')+
  geom_vline(xintercept=6)+
  facet_wrap(~name,scales="free",nrow=1)+
  theme_bw(base_size=8)+
  scale_x_continuous(breaks=seq(0,18,1))

g=ggplot(t_gt %>% filter(name %in% c("amy1_sum","AMY2A","AMY2B")) %>% filter(grepl("SGDP",sample)))
g+geom_histogram(aes(x=gt),binwidth=0.05)+
  facet_wrap(~name,scales="free",nrow=1)+
  theme_bw(base_size=8)+
  scale_x_continuous(breaks=seq(0,18,1))

g=ggplot(t_gt %>% filter(name %in% c("amy1_sum","AMY2A","AMY2B")) %>% filter(grepl("SGDP",sample)))
g+geom_histogram(aes(x=gt*1.05),binwidth=0.05,color="blue")+
  geom_vline(xintercept=c(6,8,10))+
  facet_wrap(~name,scales="free",nrow=1)+
  theme_bw(base_size=8)+
  scale_x_continuous(breaks=seq(0,18,1))

g=ggplot(t_gt %>% filter(name %in% c("amy1_sum","AMY2A","AMY2B")) %>% filter(grepl("GTEx",sample)))
g+geom_histogram(aes(x=gt),binwidth=0.05)+
  geom_vline(xintercept=c(6,8,10))+
  facet_wrap(~name,scales="free",nrow=1)+
  theme_bw(base_size=8)+
  scale_x_continuous(breaks=seq(0,18,1))

g=ggplot(t_gt %>% filter(name %in% c("amy1_sum","AMY2A","AMY2B")) %>% filter(grepl("GTEx",sample)) %>% mutate(gt=ifelse(name=="amy1_sum",gt*0.9,gt)))
g+geom_histogram(aes(x=gt),binwidth=0.05,color="blue")+
  geom_vline(xintercept=c(6,8,10))+
  facet_wrap(~name,scales="free",nrow=1)+
  theme_bw(base_size=8)+
  scale_x_continuous(breaks=seq(0,18,1))

g=ggplot(t_gt %>% filter(name %in% c("amy1_sum","AMY2A","AMY2B")) %>% filter(grepl("StoneAgeAncient",sample)))
g+geom_histogram(aes(x=gt),binwidth=0.05)+
  facet_wrap(~name,scales="free",nrow=1)+
  theme_bw(base_size=8)+
  scale_x_continuous(breaks=seq(0,18,1))

g=ggplot(t_gt %>% filter(name %in% c("amy1_sum","AMY2A","AMY2B")) %>% filter(grepl("Archaic",sample)))
g+geom_histogram(aes(x=gt),binwidth=0.05)+
  facet_wrap(~name,scales="free",nrow=1)+
  theme_bw(base_size=8)+
  scale_x_continuous(breaks=seq(0,18,1),lim=c(0,20))

g=ggplot(t_gt %>% filter(name %in% c("amy1_sum","AMY2A","AMY2B")) %>% filter(grepl("Archaic",sample)) %>% mutate(gt=ifelse(name=="amy1_sum",gt*0.8,gt)))
g+geom_histogram(aes(x=gt),binwidth=0.05,color='blue')+
  facet_wrap(~name,scales="free",nrow=1)+
  theme_bw(base_size=8)+
  scale_x_continuous(breaks=seq(0,18,1),lim=c(0,20))


g=ggplot(t_gt %>% filter(name %in% c("amy1_sum","AMY2A","AMY2B")) %>% filter(grepl("Excof",sample)))
g+geom_histogram(aes(x=gt),binwidth=0.05)+
  facet_wrap(~name,scales="free",nrow=1)+
  theme_bw(base_size=8)+
  scale_x_continuous(breaks=seq(0,18,1))

g=ggplot(t_gt %>% filter(name %in% c("amy1_sum","AMY2A","AMY2B")) %>% filter(grepl("Haak",sample)))
g+geom_histogram(aes(x=gt),binwidth=0.05)+
  facet_wrap(~name,scales="free",nrow=1)+
  theme_bw(base_size=8)+
  scale_x_continuous(breaks=seq(0,18,1),lim=c(0,20))
```
```{r}
#### MODIFY THE SGDP AND HGDP BY A CONSTANT FACTOR SO THEY FIT INTEGERS
#### This is likely due to GC bias in these libraries
#HGDP 0.97
#SGDP 1.05
#ARCHAIC AMY1 0.8
######ARCHAIC FIX
#Archaics consistently have a slight excess of coverage over the AMY1 copies, 
#potentially due to gene conversion, resulting in consistent non-mendelian copy 3 (~2.5) estimates
#this code is to correct for this

# arch_AMY1_adj = 2-(to_gt_AMY1 %>% filter(grepl("Neand|Denis",sample)) %>% summarize(mu = mean(gt)))$mu
# to_gt_AMY1=to_gt_AMY1 %>% mutate(gt = ifelse(grepl("Neand|Denis",sample),gt+arch_AMY1_adj,gt))

t_gt_adj = t_gt %>% mutate(gt=ifelse(dataset=="SGDP",gt*1.05,gt)) %>%
                    mutate(gt=ifelse(dataset=="HGDP",gt*0.97,gt)) %>%
                    mutate(gt=ifelse((dataset=="GTEx")&(name=="amy1_sum"),gt*0.8,gt)) %>%
                    mutate(gt=ifelse((dataset=="Archaic")&(name=="amy1_sum"),gt*0.9,gt)) %>%
                    filter(dataset %in% c("1KG","1KG_trio","Archaic","HGDP","SGDP","StoneAgeAncient","GTEx"))

unique(t_gt_adj$dataset)
length(unique(t_gt_adj$sample))
t_gt_adj %>% filter(dataset=="Archaic")

to_gt_AMY2A = t_gt_adj %>% filter(name=="AMY2A")  %>% dplyr::select(sample,gt)
to_gt_AMY2B = t_gt_adj %>% filter(name=="AMY2B")  %>% dplyr::select(sample,gt)
to_gt_AMY1 =  t_gt_adj %>% filter(name=="amy1_sum")  %>% dplyr::select(sample,gt)
```

```{r}
###FUNCTIONS

E_step = function(X,k,mu,offset,sigma,pi,iter){
  #calc responsibilities
  resps = list()
  for (i in seq(k)){
    resps[[i]] = data.frame(r=dnorm(X,mu[i]+offset,sigma)*pi[i],i=i,X=X,iter=iter) %>% mutate(obs=row_number())
  }
  df_resps = do.call(rbind, resps) %>%
    group_by(obs) %>%
    mutate(t = sum(r)) %>%
    mutate(r=r/t) %>%
    dplyr::select(r,obs,i,X)
  return(df_resps)
}

M_step = function(df_resps,k,mu,offset,iter){
  #update sigma, pi
  pi = (df_resps %>% 
        group_by(i) %>%
        summarize(pi = sum(r)))$pi

  pi = pi/sum(pi)
  ###HOW DO I UPDATE THE OFFSET!??!
  
  ###HAVE NOT ADDED OFFSET YET!!! who bfoken?
  num = df_resps %>% 
    ungroup() %>%
    inner_join(data.frame(mu=mu+offset) %>% mutate(i=row_number()),on=i) %>%
    summarize(num=sum(r*(X-mu)^2))
  
  denom = df_resps %>% 
          ungroup() %>%
          summarize(den=sum(r))
  sigma = sqrt(num$num/denom$den)

  mu_total_num = df_resps %>% 
    ungroup() %>%
    inner_join(data.frame(mu=mu+offset) %>% mutate(i=row_number()),on=i) %>%
    summarize(num=sum(r*X))
  
    
  updated_mu_num = df_resps %>% 
    group_by(i) %>%
    inner_join(data.frame(mu=mu+offset) %>% mutate(i=row_number()),on=i) %>%
    summarize(num=sum(r*X)) 
  
  updated_mu_denom = df_resps %>% 
    group_by(i) %>%
    inner_join(data.frame(mu=mu+offset) %>% mutate(i=row_number()),on=i) %>%
    summarize(denom=sum(r)) 

  updated_mu = updated_mu_num$num/updated_mu_denom$denom
  delta_mu = mu-updated_mu
  offset = mean(delta_mu)
  #offset=0
  #set offset = 0 here if you like
    
  return(list("sigma"=sigma,
              "pi"=pi,
              "offset"=offset,
              "iter"=iter))
}

get_dists = function(k,mx_copy,mu,offset,sigma,pi,iter){
  plot_df = list()
  for (i in seq(k)){
    x_vals = seq(0,mx_copy+1,0.01)
    y_vals = pi[i]*dnorm(x_vals,mu[i]+offset,sigma)
    plot_df[[i]]=data.frame(x=x_vals,y=y_vals,i=i,iter=iter)
  }
  plot_df = do.call(rbind, plot_df)
  return(plot_df)
}

#to_gt has samples and gts
gt_likelihood_table = function(to_gt, k,mu,offset,sigma, pi, label){
  final_resps = E_step(to_gt$gt,k,mu,offset,sigma,pi,-1)

  final_resps = to_gt %>% 
    mutate(obs=row_number()) %>%
    inner_join(final_resps,by="obs") %>%
    inner_join(data.frame(cp=mu) %>% mutate(i=row_number()),by="i") %>%
    mutate(label=label) %>%
    dplyr::select(sample, obs, r, i, X, cp, label)
  return(final_resps)
}


genotype = function(to_gt, iters, label){

  ### number of clusters
  mn_copy = round(min(to_gt$gt))
  mx_copy = round(max(to_gt$gt))
  k = mx_copy - mn_copy + 1
  
  ##initialize parameters
  mu = seq(mn_copy,mx_copy)
  pi = rep(1/k,k)
  sigma = 0.5
  offset = 0
  
  ##data
  X = to_gt$gt
  
  params = list()
  dists = list()
  dists[[1]] = get_dists(k,mx_copy,mu,offset,sigma,pi,1)
  
  for (j in seq(2,iters)){
    df_resps = E_step(X,k,mu,offset,sigma,pi,j)
    params = M_step(df_resps,k,mu,offset,j)
    pi = params$pi
    sigma = params$sigma
    offset = params$offset
    dists[[j]] = get_dists(k,mx_copy,mu,offset,sigma,pi,j)
  }
  dists = do.call(rbind, dists)
  
  final_resps = gt_likelihood_table(to_gt,k,mu,offset,sigma, pi, label)
  
  #final_resps = E_step(X,k,mu,offset,sigma,pi,-1)

  #final_resps = to_gt %>% 
  #  mutate(obs=row_number()) %>%
  #  inner_join(final_resps,by="obs") %>%
  #  inner_join(data.frame(cp=mu) %>% mutate(i=row_number()),by="i") %>%
  #  mutate(label=label) %>%
  #  dplyr::select(sample, obs, r, i, X, cp, label)

  return(list("k"=k,
              "mu"=mu,
              "offset"=offset,
              "sigma"=sigma,
              "pi"=pi,
              "dists"=dists,
              "final_resps"=final_resps))
}

```


```{r}
#Original TRAIN on 1kg, but use on others
#undebug(M_step)
#genotype(to_gt_train_AMY1, 20, "AMY1")

AMY1_gt = genotype(to_gt_AMY1, 20, "AMY1")
AMY2B_gt = genotype(to_gt_AMY2B, 20, "AMY2B")
AMY2A_gt = genotype(to_gt_AMY2A, 20, "AMY2A")


#MY2Ap_gt_trained = genotype(to_gt_train_AMY2Ap, 20, "AMY2Ap")
                             
# gtl_AMY1 = gt_likelihood_table(t_gt %>% filter(name=="amy1_sum") %>% dplyr::select(sample,gt), 
#                                AMY1_gt_trained$k,
#                                AMY1_gt_trained$mu,
#                                AMY1_gt_trained$offset,
#                                AMY1_gt_trained$sigma, 
#                                AMY1_gt_trained$pi, 
#                                "AMY1")
# 
# gtl_AMY2A = gt_likelihood_table(t_gt %>% filter(name=="AMY2A") %>% dplyr::select(sample,gt), 
#                                AMY2A_gt_trained$k,
#                                AMY2A_gt_trained$mu,
#                                AMY2A_gt_trained$offset,
#                                AMY2A_gt_trained$sigma, 
#                                AMY2A_gt_trained$pi, 
#                                "AMY2A")
# 
# gtl_AMY2B = gt_likelihood_table(t_gt %>% filter(name=="AMY2B") %>% dplyr::select(sample,gt), 
#                                AMY2B_gt_trained$k,
#                                AMY2B_gt_trained$mu,
#                                AMY2B_gt_trained$offset,
#                                AMY2B_gt_trained$sigma, 
#                                AMY2B_gt_trained$pi, 
#                                "AMY2B")
# 
# gtl_AMY2Ap = gt_likelihood_table(t_gt %>% filter(name=="AMY2Ap") %>% dplyr::select(sample,gt), 
#                                AMY2Ap_gt_trained$k,
#                                AMY2Ap_gt_trained$mu,
#                                AMY2Ap_gt_trained$offset,
#                                AMY2Ap_gt_trained$sigma, 
#                                AMY2Ap_gt_trained$pi, 
#                                "AMY2Ap")



all_gts = rbind(AMY1_gt$final_resps,
                AMY2B_gt$final_resps,
                AMY2A_gt$final_resps)

outdir="/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/read_depth_genotyping/genotyping/output"
fn_gts = paste(outdir,"/genotypes.likelihoods.tsv",sep="")
write.table(all_gts, fn_gts, sep="\t",row.names = FALSE, quote = FALSE)



gtl_AMY2B = gt_likelihood_table(t_gt %>% filter(name=="AMY2B") %>% dplyr::select(sample,gt),
                               AMY2B_gt$k,
                               AMY2B_gt$mu,
                               AMY2B_gt$offset,
                               AMY2B_gt$sigma,
                               AMY2B_gt$pi,
                               "AMY2B")

AMY1_gt$final_resps %>% filter(grepl("Neander",sample)) 

```
```{r}

AMY1_gt[["offset"]]
AMY2A_gt[["offset"]]
AMY2B_gt[["offset"]]

outdir="/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/read_depth_genotyping/genotyping/output_figures/genotyping"

adj = 500
g=ggplot(AMY1_gt$dists %>% filter(iter==20))+
  geom_histogram(aes(x=gt, fill=dataset),binwidth = 0.1,data=to_gt_AMY1 %>% separate(sample,c("dataset","ID","p1","p2"),sep="\\.",remove=FALSE))+
  geom_line(aes(x=x,y=y*adj,group=factor(i)),size=.5,alpha=.7)+
  theme_bw()+
  theme(legend.position=c(0.7,0.8),
        legend.background=element_blank(),
        legend.key.size=unit(0.25,"cm"),
        legend.text = element_text(size=8))+
  scale_x_continuous(breaks=seq(0,20,2)) +
  scale_fill_brewer("",palette="Set1")+
  scale_y_continuous("count/density")

print(g)
fn_out = paste(outdir,"/AMY1_genotyping.pdf",sep="")
pdf(fn_out,width=3,height=2)
print(g)
dev.off()


g=ggplot(AMY2A_gt$dists %>% filter(iter==20))+
  geom_histogram(aes(x=gt, fill=dataset),binwidth = 0.1,data=to_gt_AMY2A%>% separate(sample,c("dataset","ID","p1","p2"),sep="\\.",remove=FALSE))+
  geom_line(aes(x=x,y=y*adj,group=factor(i)),size=.5,alpha=.7)+
  theme_bw()+
  theme(legend.position=c(0.7,0.8),
        legend.background=element_blank(),
        legend.key.size=unit(0.25,"cm"),
        legend.text = element_text(size=8))+
  scale_x_continuous(breaks=seq(0,20,2)) +
  scale_fill_brewer("",palette="Set1")+
  scale_y_continuous("count/density")

print(g)
fn_out = paste(outdir,"/AMY2A_genotyping.pdf",sep="")
pdf(fn_out,width=3,height=2)
print(g)
dev.off()

g=ggplot(AMY2B_gt$dists %>% filter(iter==20))+
  geom_histogram(aes(x=gt, fill=dataset),binwidth = 0.1,data=to_gt_AMY2B%>% separate(sample,c("dataset","ID","p1","p2"),sep="\\.",remove=FALSE))+
  geom_line(aes(x=x,y=y*adj,group=factor(i)),size=.5,alpha=.7)+
  theme_bw()+
  theme(legend.position=c(0.7,0.8),
        legend.background=element_blank(),
        legend.key.size=unit(0.25,"cm"),
        legend.text = element_text(size=8))+
  scale_x_continuous(breaks=seq(0,20,2)) +
  scale_fill_brewer("",palette="Set1")+
  scale_y_continuous("count/density")

print(g)
fn_out = paste(outdir,"/AMY2B_genotyping.pdf",sep="")
pdf(fn_out,width=3,height=2)
print(g)
dev.off()



```

```{r}

best_cp =  rbind(gtl_AMY2B,gtl_AMY1,gtl_AMY2A,gtl_AMY2Ap) %>%
            group_by(sample,label) %>%
            filter(r==max(r)) %>%
            separate(sample,c("source","sample_id",'p1','p2'),remove=FALSE,sep="\\.")
            

outdir="/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/read_depth_genotyping/genotyping/output_figures"
fn_gts = paste(outdir,"/maximum_likelihood_genotypes.pdf",sep="")
pdf(fn_gts,width=8,height=4)
g=ggplot(best_cp)
g+geom_histogram(aes(x=X,fill=factor(cp)),binwidth=.05)+
  theme_bw()+
  scale_fill_manual(values=sample(viridisLite::turbo(20)))+
  scale_x_continuous(breaks=seq(0,20,2))+
  #facet_grid(source~label,scales="free")
  facet_wrap(source~label,scales="free",switch = "bottom")+
  theme(strip.background = element_blank(),
        strip.text = element_text(size=4))
  #scale_y_log10()
  #coord_cartesian(ylim=c(0,5))

dev.off()
```

```{r}
outdir="/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/output/d4"
fn_out = paste(outdir,"/gmm_genotypes.pdf",sep="")


adj = 250
g=ggplot(dists)+
  geom_histogram(aes(x=gt),data=to_gt,binwidth = 0.1)+
  geom_line(aes(x=x,y=y*adj,color=factor(i)))+
  theme_bw()+
  facet_wrap(~iter)+
  theme(legend.position="None")+
  scale_x_continuous(breaks=seq(0,mx_copy))

outdir="/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/output/d4"
fn_out = paste(outdir,"/gmm_genotypes.pdf",sep="")
#pdf(fn_out,width=8,height=5)
#print(g)
#dev.off()

g=ggplot(dists %>% filter(iter==20))+
  geom_histogram(aes(x=gt),data=to_gt,binwidth = 0.1)+
  geom_line(aes(x=x,y=y*adj,color=factor(i)))+
  theme_bw()+
  facet_wrap(~iter)+
  theme(legend.position="None")+
  scale_x_continuous(breaks=seq(0,mx_copy))
print(g)

final_resps = E_step(X,k,mu,offset,sigma,pi,-1)

final_resps = to_gt %>% 
  mutate(obs=row_number()) %>%
  inner_join(final_resps,by="obs") %>%
  inner_join(data.frame(cp=mu) %>% mutate(i=row_number()),by="i")



# params = M_step(df_resps,k,mu,resps,1)
# pi = params$pi
# sigma = params$sigma
# 
# ggplot(get_dists(k,mx_copy,mu,sigma,pi))+
#   geom_line(aes(x=x,y=y,color=factor(i)))+theme_bw()
# 
# df_resps = E_step(X,k,mu,sigma,pi,2)
# params = M_step(df_resps,k,mu,resps,1)
# pi = params$pi
# sigma = params$sigma
# 
# ggplot(get_dists(k,mx_copy,mu,sigma,pi))+
#   geom_line(aes(x=x,y=y,color=factor(i)))+theme_bw()
# 
```

```{r}

### EXPERIMENTING WITH GENOTYPING and plotting
 
AMY1_ALL = t_gt %>% filter(name=="amy1_sum")

AMY1_1kg_gt = genotype(AMY1_1kg, 20, "AMY1")
AMY1_HGDP_gt = genotype(AMY1_HGDP, 20, "AMY1")
AMY1_ALL_gt = genotype(AMY1_ALL, 20, "AMY1")


AMY1_1kg_gt[["offset"]]
AMY1_HGDP_gt[["offset"]]
AMY1_ALL_gt[["offset"]]

adj = 250
g=ggplot(AMY1_1kg_gt$dists %>% filter(iter==20))+
  geom_histogram(aes(x=gt),binwidth = 0.1,data=AMY1_1kg)+
  geom_line(aes(x=x,y=y*adj,color=factor(i)))+
  theme_bw()+
  facet_wrap(~iter)+
  theme(legend.position="None")+
  scale_x_continuous(breaks=seq(0,20,2))

print(g)

adj = 120
g=ggplot(AMY1_HGDP_gt$dists %>% filter(iter==20))+
  geom_histogram(aes(x=gt),binwidth = 0.05,data=AMY1_HGDP)+
  geom_line(aes(x=x,y=y*adj,color=factor(i)))+
  theme_bw()+
  facet_wrap(~iter)+
  theme(legend.position="None")+
  scale_x_continuous(breaks=seq(0,20,2))

print(g)

adj = 120
g=ggplot(AMY1_ALL_gt$dists %>% filter(iter==20))+
  geom_histogram(aes(x=gt),binwidth = 0.05,data=AMY1_ALL)+
  geom_line(aes(x=x,y=y*adj,color=factor(i)))+
  theme_bw()+
  facet_wrap(~iter)+
  theme(legend.position="None")+
  scale_x_continuous(breaks=seq(0,20,2))

print(g)

AMY1_ALL_gt$final_resps %>% 
  group_by(sample) %>%
  filter(r==max(r)) %>%
  filter(grepl("Neander",sample))

```

```{r}

mus = x_amy1$parameters$mean
weights = x_amy1$parameters$pro
var = x_amy1$parameters$variance$sigmasq

x_vals = seq(0,6,0.01)
y_vals = x_vals*0
  
for (i in seq(1,9)){
  #y_vals = y_vals + weights[i]*dnorm(x_vals,mus[i],sqrt(var))
  y_vals = y_vals + weights[i]*dnorm(x_vals,mus[i],sqrt(var))
}
E_step = function(X,k,mu,sigma,pi,iter){
  # grid <- seq()
  #   expand.grid(x = seq(0, 6, length.out=200), y = seq(40, 100, length.out=200))
  # G1 = cbind(grid, p=dmvnorm(grid, mu[[1]], cov[[1]])*a[[1]]) %>% mutate(d="G1")
  # G2 = cbind(grid, p=dmvnorm(grid, mu[[2]], cov[[2]])*a[[2]]) %>% mutate(d="G2")
  # df_dists = rbind(G1,G2) %>% mutate(iteration=iteration)
  
  resps = list()
  t_gt[[i]]=t_sub_gt
  
  for (i in seq(k)){
    resps[[i]] = data.frame(r=dnorm(X,mu[i],sigma)*pi[i],i=i) %>% mutate(obs=row_number())
  }
  resps = do.call(rbind, resps) %>%
    group_by(obs) %>%
    mutate(t = sum(r))
  return resps
  # df_resps = cbind(X, dnorm(X,mus[1],sqrt(var))
  #                  
  #                 G1=dmvnorm(as.matrix(data), mu[[1]], cov[[1]])*pi[[1]],
  #                 G2=dmvnorm(as.matrix(data), mu[[2]], cov[[2]])*pi[[2]]) %>%
  #           mutate(t=G1+G2) %>%
  #           gather(key=d, value=r,-c(x,y,t)) %>%
  #           mutate(r=r/t) %>%
  #           mutate(iteration=iteration)
  
  # return(list("df_dists"=df_dists,
  #             "df_resps"=df_resps))
}

```