---
title: "Untitled"
output: html_document
date: "2022-08-12"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)
#library(ggforce)
library(ggsankey)
library(PNWColors)

pop_info = read.table("/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/haplotype_analysis/metadata/modern_and_ancient_european.tsv",header=T,sep="\t") %>% 
    mutate(popGrouping = ifelse(popGrouping %in% c("CEU","TSI","GBR","FIN","IBS"),
                                "modern European",
                                paste("ancient ",popGrouping,sep=""))) %>%
    mutate(popGrouping = ifelse(grepl("Hunter",popGrouping),"ancient Hunter-Gatherer",popGrouping))

pop_info = read.table("/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/haplotype_analysis/metadata/1000_genomes_simple_EASTASIA.tsv",header=T,sep="\t") %>%
  mutate(popGrouping=POPULATION)

EAST_ASIA = c("CHB","JPT","CHS","CDX","KHV","CHD")
EUROPE = c("TSI","GBR","FIN")
EUROPE_2 = c("CEU","IBS")
AFRICA = c("YRI","LWK","GWD","MSL","ESN")
ADMIXED = c("ASW","ACB","MXL","PUR","CLM","PEL")
SOUTH_ASIA = c("GIH","PJL","BEB","STU","ITU")

pop_info = read.table("/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/haplotype_analysis/metadata/1000_genomes_simple.tsv",header=T,sep="\t") %>%
  mutate(popGrouping=POPULATION) %>%
  mutate(popGrouping =
           case_when(
              popGrouping %in% EAST_ASIA ~ "EAST_ASIA",
              popGrouping %in% EUROPE ~ "EUROPE",
              popGrouping %in% EUROPE_2 ~ "EUROPE_2",
              popGrouping %in% AFRICA ~ "AFRICA",
              popGrouping %in% ADMIXED ~ "ADMIXED",
              popGrouping %in% SOUTH_ASIA ~ "SOUTH_ASIA",
              popGrouping %in% TRUE ~ "---"))
  

pop_info = read.table("/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/haplotype_analysis/metadata/1000_genomes_simple_ALL_plus_ancient.tsv",header=T,sep="\t") %>%
  mutate(popGrouping =
           case_when(
              popGrouping %in% EAST_ASIA ~ "modern-EAST_ASIA",
              popGrouping %in% EUROPE ~ "modern-EUROPE",
              popGrouping %in% EUROPE_2 ~ "modern-EUROPE_2",
              popGrouping %in% AFRICA ~ "modern-AFRICA",
              popGrouping %in% ADMIXED ~ "modern-ADMIXED",
              popGrouping %in% SOUTH_ASIA ~ "modern-SOUTH_ASIA",
              TRUE ~ paste("ancient",popGrouping,sep="-")))

#write.table(pop_info,"/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/haplotype_analysis/metadata/modernALL_ancientEuro_relabled.tsv",sep="\t",row.names = FALSE,quote = FALSE)
```



```{r}

outdir="/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/haplotype_analysis/output"

#t = read.table("/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/haplotype_analysis/output/AMY_100000_EUROPEAN.tsv",sep="\t",header=TRUE)
#t = read.table("/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/haplotype_analysis/output/AMY_100000_modern-ancient-EUR.tsv",sep="\t",header=TRUE)
#t = read.table("/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/haplotype_analysis/output/AMY_100000_EASTASIA.tsv",sep="\t",header=TRUE)
#fn_out = paste(outdir,"/100kb_modern_ancient_euro_AMY_samples_colored_paths.png",sep="")

#t = read.table("/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/haplotype_analysis/output/AMY_100000_EASTASIA.tsv",sep="\t",header=TRUE)
#fn_out = paste(outdir,"/100kb_modern_ASIA_AMY_samples_colored_paths.png",sep="")
#t = read.table("/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/haplotype_analysis/output/AMY_100000_modern.tsv",sep="\t",header=TRUE)
#fn_out = paste(outdir,"/100kb_modern_ALL_AMY_samples_colored_paths.png",sep="")

#t = read.table("/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/haplotype_analysis/output/AMY_100000_modern-ancient-EUR.tsv",sep="\t",header=TRUE)
#fn_out = paste(outdir,"/100kb_modern_EUROPE_AMY_samples_w_ancients_colored_paths.png",sep="")
#colors =pnw_palette("Bay",5)

#t = read.table("/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/haplotype_analysis/output/AMY_100000_modern-ancient.tsv",sep="\t",header=TRUE)
#fn_out = paste(outdir,"/100kb_modern_ALL_AMY_samples_w_ancients_colored_paths.png",sep="")
#colors =pnw_palette("Bay",8)




###PLOT haplotgraph
t = read.table("/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/amylase_diversity_project/haplotype_analysis/output/AMY_50000_modern-ancient.tsv",sep="\t",header=TRUE) %>%
  mutate(dir=ifelse(dir=="left","distal","proximal"))

fn_out = paste(outdir,"/50kb_modern_ALL_AMY_samples_w_ancients_colored_paths.png",sep="")
fn_out_2 = paste(outdir,"/50kb_modern_ALL_AMY_samples_w_ancients_haploslice.png",sep="")
fn_out_3 = paste(outdir,"/50kb_modern_ALL_AMY_samples_w_ancients_allele_trajectories.png",sep="")
colors =pnw_palette("Bay",8)


pops = c("ancient-Early Farmer",
        "ancient-Yamnaya",
        "modern-EUROPE",
        "ancient-Hunter-Gatherer (E)",
        "ancient-Hunter-Gatherer (W)")

pop_info_of_interest = pop_info %>% filter(popGrouping %in% pops)

space=100
t_node = t %>%
  filter(sample %in% pop_info_of_interest$sample) %>%
  group_by(position,node,dir) %>%
  #dplyr::group_by_all() %>%
  dplyr::summarise(freq = dplyr::n(), .groups="keep") %>%
  ungroup() %>%
  group_by(position,dir) %>%
  dplyr::mutate(ymax = cumsum(freq) + (dplyr::row_number() - 1)*space,
                ymin = ymax - freq) %>%
  dplyr::mutate(ymin = ymin - max(ymax)/2,
                ymax = ymax - max(ymax)/2) %>%
  dplyr::ungroup()

t_indiv_paths = inner_join(t,t_node,by=c("position","node","dir")) %>%
                filter(sample %in% pop_info_of_interest$sample) %>%
                group_by(position,node) %>%
                mutate(path_y = ymin+row_number()) %>%
                inner_join(pop_info,on="sample")



#g+geom_segment(aes(x=position,xend=position,y=ymin,yend=ymax),data=t_node)+
#pos=104327640
#pos=104323618
#pos=104093439
#pos=104098057
#dir="distal"
#dir="proximal"

mx_pos = 104327640
mx_pos = 104350000

mn_pos = 104093439
mn_pos = 104070000

mn_prox = min(t  %>% filter(dir=="proximal") %>% dplyr::select(position))
mx_dist = max(t %>% filter(dir=="distal") %>% dplyr::select(position))


positions = t_indiv_paths %>% ungroup() %>%
            dplyr::select(position,dir) %>%
            unique() %>% filter(position<mx_pos,
                                position>mn_pos) %>%
            filter(!position %in% c(mn_prox,mx_dist))

g=ggplot(t_indiv_paths)
g=g+geom_segment(aes(x=position,xend=next_pos,y=path_y,yend=path_y,color=popGrouping),
               size=.01,
               alpha=1)+
  #scale_color_viridis_d()+
  theme_bw(base_size=6)+
  guides(color=guide_legend(override.aes = list(size=1)))+
  theme(panel.grid = element_blank())+
  facet_grid(.~dir,scales="free_x")+
  scale_color_manual(values=colors)+
  theme(strip.background=element_blank(),
        panel.border = element_blank(),
        legend.key.size = unit(.1,"cm"))+
  geom_vline(aes(xintercept = position),
             data=positions,
             linetype="dotted",
             alpha=0.5)
  

#fn_out = paste(outdir,"/100kb_modern_ancient_euro_AMY_samples_colored_paths.png",sep="")
png(fn_out,width=6.5,height=3,units='in',res=600)
print(g)
dev.off()

```


```{r}

pops = c("ancient-Early Farmer",
        "ancient-Yamnaya",
        "modern-EUROPE",
        "ancient-Hunter-Gatherer (E)",
        "ancient-Hunter-Gatherer (W)")

t_hap_by_age = t_indiv_paths %>% ungroup() %>%
      filter(popGrouping %in% pops) %>%
      mutate(year_bin = case_when(
            ageAverage >8000 ~ 5,
            ageAverage >6000 ~ 4,
            ageAverage >4700 ~ 3,
            ageAverage >3500 ~ 2,
            ageAverage >0 ~ 1,
            TRUE ~ 0)) %>%
  #filter(position == pos) %>%
  filter(position%in%positions$position) %>% 
  group_by(position,dir) %>%
  mutate(total_haps = n()) %>%
  group_by(year_bin,position,dir) %>%
  mutate(total_n_of_age = n()) %>%
  ungroup() %>%
  group_by(node,total_haps,total_n_of_age,position,dir) %>%
  mutate(node=node,node_size=n()) %>%
  group_by(year_bin,node_size,node,total_haps,total_n_of_age,position,dir) %>%
  summarize(n_age = n()) %>%
  mutate(pop_prop_of_node = n_age/node_size,
         node_prop_of_total = node_size/total_haps) %>%
  mutate(node_prop_of_age=n_age/total_n_of_age) 
  

cutoff = 0.05

t_age_plot_gt = t_hap_by_age %>% 
  filter(node_prop_of_age>=cutoff) %>%
  dplyr::select(year_bin,node,node_prop_of_age,position,dir) %>%
  mutate(node = as.character(node))

t_age_plot_lt = t_hap_by_age %>% 
  filter(node_prop_of_age<cutoff) %>%
  group_by(year_bin,position,dir) %>%
  summarize(node_prop_of_age=sum(node_prop_of_age)) %>%
  mutate(node=paste("<",cutoff*100,"%")) %>%
  dplyr::select(year_bin,node,node_prop_of_age,position,dir)

t_plot_age = rbind(t_age_plot_gt,t_age_plot_lt) %>%
             ungroup() %>%
             mutate(f = node_prop_of_age) %>%
             dplyr::select(position,node,dir,f,year_bin) %>%
             pivot_wider(names_from = year_bin,
                         values_from = f) %>%
             mutate(delta = `1` - `5`) %>%
             #mutate(delta = `0` - `5`) %>%
             filter(!is.na(delta)) %>%
             pivot_longer(-c(position, node, dir, delta),names_to="year_bin",values_to="f",values_drop_na = TRUE) %>%
             group_by(position) %>%
             mutate(max_delta = max(delta)) %>%
             mutate(traj_inc = delta==max_delta) %>%
             mutate(year_bin = as.numeric(year_bin))

selection_coefs = t_plot_age %>% 
  filter(traj_inc) %>% 
  pivot_wider(names_from = year_bin,
              values_from = f) %>%
  # mutate(d=delta/(8000/25),
  #        p=`5`,
  #        q=1-`5`) %>%
  mutate(d=delta/(4500/25),
         p=`4`,
         q=1-`4`) %>%
  mutate(s=2*d / (q*(d+p)*(p+2*q))) %>%
  dplyr::select(position,dir,s) %>%
  mutate(label = paste("s==",signif(s,2),sep=""),x=-3,y=.75)


colors = c("black","red")
g=ggplot(t_plot_age)
g=g+geom_point(aes(x=-year_bin,y=f,color=traj_inc,group=node))+
  geom_line(aes(x=-year_bin,y=f,color=traj_inc,group=node))+
  geom_text(aes(x=x,y=y,label=label),parse=TRUE,data=selection_coefs,size=2)+
  theme_bw(base_size=6)+
  theme(legend.key.size=unit(.5,"cm"))+
  #scale_color_viridis_d("Haplotype Node",option="A")+
  scale_color_manual("Haplotype Node",values=colors)+
  scale_x_continuous("sample age",labels = age_bins,breaks=seq(-5,0,1))+
  scale_y_continuous("f") +
  facet_wrap(dir~position)+
  theme(legend.position="None",
        strip.background = element_blank())

png(fn_out_3,width=6,height=6,units='in',res=600)
print(g)
dev.off()

unique(t_indiv_paths$popGrouping)
#0.009/0.02

```

```{r}
age_bins = c(">8000","6000-8000","4700-6000","3500-4700","<3500","current")
t_hap_by_age = t_indiv_paths %>% ungroup() %>%
      mutate(year_bin = case_when(
            ageAverage >8000 ~ 5,
            ageAverage >6000 ~ 4,
            ageAverage >4700 ~ 3,
            ageAverage >3500 ~ 2,
            ageAverage >0 ~ 1,
            TRUE ~ 0)) %>%
  filter(position==pos) %>%
  mutate(total_haps = n()) %>%
  group_by(year_bin) %>%
  mutate(total_n_of_age = n()) %>%
  ungroup() %>%
  group_by(node,total_haps,total_n_of_age) %>%
  mutate(node=node,node_size=n()) %>%
  group_by(year_bin,node_size,node,total_haps,total_n_of_age) %>%
  summarize(n_age = n()) %>%
  mutate(pop_prop_of_node = n_age/node_size,
         node_prop_of_total = node_size/total_haps) %>%
  mutate(node_prop_of_age=n_age/total_n_of_age) 
  
cutoff = 0.05

t_age_plot_gt = t_hap_by_age %>% 
  filter(node_prop_of_age>=cutoff) %>%
  dplyr::select(year_bin,node,node_prop_of_age) %>%
  mutate(node = as.character(node))

t_age_plot_lt = t_hap_by_age %>% 
  filter(node_prop_of_age<cutoff) %>%
  group_by(year_bin) %>%
  summarize(node_prop_of_age=sum(node_prop_of_age)) %>%
  mutate(node=paste("<",cutoff*100,"%")) %>%
  dplyr::select(year_bin,node,node_prop_of_age)

t_plot_age = rbind(t_age_plot_gt,t_age_plot_lt)

g=ggplot(t_plot_age)
g=g+geom_point(aes(x=-year_bin,y=node_prop_of_age,color=factor(node)))+
  geom_line(aes(x=-year_bin,y=node_prop_of_age,color=factor(node)))+
  theme_bw(base_size=6)+
  theme(legend.key.size=unit(.5,"cm"))+
  scale_color_viridis_d("Haplotype Node")+
  scale_x_continuous("sample age",labels = age_bins,breaks=seq(-5,0,1))+
  scale_y_continuous("f")

#png(fn_out_3,width=3,height=2,units='in',res=600)
print(g)
#dev.off()


```

```{r}


node_props = t_indiv_paths %>% 
  ungroup() %>%
  filter(position==pos) %>%
  mutate(total_haps = n()) %>%
  group_by(popGrouping) %>%
  mutate(total_n_of_pop = n()) %>%
  ungroup() %>%
  group_by(node,total_haps,total_n_of_pop) %>%
  mutate(node=node,node_size=n()) %>%
  group_by(popGrouping,node_size,node,total_haps,total_n_of_pop) %>%
  summarize(n_pop = n()) %>%
  mutate(pop_prop_of_node = n_pop/node_size,
         node_prop_of_total = node_size/total_haps) %>%
  mutate(node_prop_of_pop=n_pop/total_n_of_pop) 

age_bins = c(">8000","6000-8000","4700-6000","3500-4700","<3500","current")
t_hap_by_age = t_indiv_paths %>% 
      mutate(year_bin = case_when(
            ageAverage >8000 ~ 5,
            ageAverage >6000 ~ 4,
            ageAverage >4700 ~ 3,
            ageAverage >3500 ~ 2,
            ageAverage >0 ~ 1,
            TRUE ~ 0)) %>%
  ungroup() %>%
  filter(position==pos) %>%
  mutate(total_haps = n()) %>%
  group_by(year_bin) %>%
  mutate(total_n_of_age = n()) %>%
  ungroup() %>%
  group_by(node,total_haps,total_n_of_age) %>%
  mutate(node=node,node_size=n()) %>%
  group_by(year_bin,node_size,node,total_haps,total_n_of_age) %>%
  summarize(n_age = n()) %>%
  mutate(pop_prop_of_node = n_age/node_size,
         node_prop_of_total = node_size/total_haps) %>%
  mutate(node_prop_of_age=n_age/total_n_of_age) 
  
cutoff = 0.05

t_age_plot_gt = t_hap_by_age %>% 
  filter(node_prop_of_age>=cutoff) %>%
  dplyr::select(year_bin,node,node_prop_of_age) %>%
  mutate(node = as.character(node))

t_age_plot_lt = t_hap_by_age %>% 
  filter(node_prop_of_age<cutoff) %>%
  group_by(year_bin) %>%
  summarize(node_prop_of_age=sum(node_prop_of_age)) %>%
  mutate(node=paste("<",cutoff*100,"%")) %>%
  dplyr::select(year_bin,node,node_prop_of_age)

t_plot_age = rbind(t_age_plot_gt,t_age_plot_lt)


t_plot_gt = node_props %>% 
  filter(node_prop_of_pop>=cutoff) %>%
  dplyr::select(popGrouping,node,node_prop_of_pop) %>%
  mutate(node = as.character(node))

t_plot_lt = node_props %>% 
  filter(node_prop_of_pop<cutoff) %>%
  group_by(popGrouping) %>%
  summarize(node_prop_of_pop=sum(node_prop_of_pop)) %>%
  mutate(node=paste("<",cutoff*100,"%")) %>%
  dplyr::select(popGrouping,node,node_prop_of_pop)

t_plot = rbind(t_plot_gt,t_plot_lt)

colors = c("grey",pnw_palette("Sailboat",7))

pop_order = c("modern-AFRICA",
              "modern-EAST_ASIA",
              "modern-SOUTH_ASIA",          
              "modern-EUROPE",
              "ancient-Yamnaya",
              "ancient-Early Farmer",
              "ancient-Hunter-Gatherer (E)",
              "ancient-Hunter-Gatherer (W)")
              
t_plot$popGrouping = factor(t_plot$popGrouping,levels = pop_order)

g=ggplot(t_plot)
g=g+geom_bar(aes(x=popGrouping,y=node_prop_of_pop,fill=node),stat='identity')+
  theme_bw()+
  scale_fill_viridis_d("Haplotype Node")+
  coord_flip()
  #scale_fill_manual(values=colors)

png(fn_out_2,width=5,height=3,units='in',res=600)
print(g)
dev.off()

g=ggplot(t_plot_age)
g=g+geom_point(aes(x=-year_bin,y=node_prop_of_age,color=factor(node)))+
  geom_line(aes(x=-year_bin,y=node_prop_of_age,color=factor(node)))+
  theme_bw(base_size=6)+
  theme(legend.key.size=unit(.5,"cm"))+
  scale_color_viridis_d("Haplotype Node")+
  scale_x_continuous("sample age",labels = age_bins,breaks=seq(-5,0,1))+
  scale_y_continuous("f")

png(fn_out_3,width=3,height=2,units='in',res=600)
print(g)
dev.off()


t_indiv_paths %>% ungroup() %>% dplyr::select(position) %>% unique() %>% arrange(position)
```
```{r}
### s calc

w_hat=1-.5*q*p*s-q*q*s
d = (0.5*p*p*q*s+p*q*q*s)/(1-.5*q*p*s-q*q*s)

g=30
p_now = 0.5
p_old = 0.2
d=(p_now-p_old)/(8000/g)
p=p_old
q = 1-p_old

s = 2*d / (q*(d+p)*(p+2*q))
s

```

```{r}

t = read.table("/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/haplotype_analysis/output/LCT_100000_modern-ancient-EUR.tsv",sep="\t",header=TRUE)

  g=ggplot(t) +
  geom_sankey(aes(x = position, 
                  next_x = next_pos,
                  node = node, 
                  next_node = next_node),
              alpha=0.5,
              space=50,
              smooth=8) +
  facet_grid(.~dir,scales="free")+
  theme_alluvial(base_size = 4)+
  theme(axis.text.y=element_blank())+
  theme(legend.position="None")

outdir="/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/haplotype_analysis/output"
fn_out = paste(outdir,"/100kb_modern_ancient_euro_LCT_samples.pdf",sep="")
pdf(fn_out,width=3.5,height=3)
print(g)
dev.off()

#t %>% group_by(node,position,next_node,next_pos) %>%
#  summarize(sum = n())
# df <- gapminder %>%
#   group_by(continent, year) %>%
#   summarise(gdp = (sum(pop * gdpPercap)/1e9) %>% round(0), .groups = "keep") %>%
#   ungroup()


space=50
t_node = t %>% group_by(position,node,dir) %>%
  #dplyr::group_by_all() %>%
  dplyr::summarise(freq = dplyr::n(), .groups="keep") %>%
  ungroup() %>%
  group_by(position,dir) %>%
  dplyr::mutate(ymax = cumsum(freq) + (dplyr::row_number() - 1)*space,
                ymin = ymax - freq) %>%
  dplyr::mutate(ymin = ymin - max(ymax)/2,
                ymax = ymax - max(ymax)/2) %>%
  dplyr::ungroup()

t_indiv_paths = inner_join(t,t_node,by=c("position","node","dir")) %>%
                group_by(position,node) %>%
                mutate(path_y = ymin+row_number()) %>%
                inner_join(pop_info,on="sample")

#g+geom_segment(aes(x=position,xend=position,y=ymin,yend=ymax),data=t_node)+
  
g=ggplot(t_indiv_paths)
g=g+geom_segment(aes(x=position,xend=next_pos,y=path_y,yend=path_y,color=popGrouping),
               size=.01,
               alpha=1)+
  scale_color_manual(values=colors)+
  theme_bw()+
  guides(color=guide_legend(override.aes = list(size=1)))+
  theme(panel.grid = element_blank())+
  theme(legend.key.size=unit(0.25,"cm"))
print(g)  
outdir="/Users/petersudmant/Documents/science/sudmantlab/projects/ancient_DNA/amylase/haplotype_analysis/output"
fn_out = paste(outdir,"/100kb_modern_ancient_euro_LCT_samples_colored_paths.png",sep="")
png(fn_out,width=6.5,height=3,units='in',res=600)
print(g)
dev.off()

```

```{r}

t %>% filter(is.na(next_pos)) %>%
  group_by(node,position,dir) %>%
  summarize(sum = n()) %>%
  arrange(sum)#%>%
  #filter(sum>1000)
  #group_by(node,position,next_node,next_pos,sample,dir) 


#unique(t$sample)[1000:2000]

```


```{r}
data

df = data.frame(x=c(0,10,10),
           y=c(0,0,1),
           id=c(1,2,3),
           value=c(1,0.6,0.4))

ggplot(df, aes(x, id = id, split = y, value = value)) +
  geom_parallel_sets(alpha = 1, axis.width = 0.1)
  #geom_parallel_sets_axes(axis.width = 0.1) +
  #geom_parallel_sets_labels(colour = 'white')

```