#!vim set syntax=python
import pandas as pd

configfile: "config.json"

rule all:
    input:
        #"output/LCT_50000_modern-ancient-EUR.tsv",
        #"output/LCT_100000_modern-ancient-EUR.tsv",
        "output/AMY_100000_modern-ancient-EUR.tsv",
        "output/AMY_50000_modern-ancient-EUR.tsv",
        "output/AMY_100000_EUROPEAN.tsv",
        "output/AMY_50000_EUROPEAN.tsv",
        "output/AMY_50000_EASTASIA.tsv",
        "output/AMY_100000_EASTASIA.tsv",
        "output/AMY_100000_modern.tsv",
        "output/AMY_100000_modern-ancient.tsv",
        "output/AMY_50000_modern-ancient.tsv"


# TO DOs
# make asians
rule make_haplograph: 
    output:
        "output/{locus}_{width}_{population}.tsv"
    run:
        fn_sample_subset = config['sample_groupings'][wildcards.population]
        info = config['loci'][wildcards.locus]
        shell("python ./haplotype_graph/haploplot.py "
                    "--fn_vcf ./input/2.neo.impute.1000g.vcf.gz "
                    "--fn_out {output} "
                    "--width {width} "
                    "--contig 2 "
                    "--min_AF 0.05 "
                    "--sample_subset {fn_sample_subset} "
                    "--label {population} "
                    "--start_left {s_left} "
                    "--start_right {s_right}"
                    "".format(output=output[0],
                              population=wildcards.population,
                              width=wildcards.width,
                              s_left = config['loci'][wildcards.locus]['start_left'],
                              s_right = config['loci'][wildcards.locus]['start_right'],
                              fn_sample_subset=fn_sample_subset))
        
